### ISSUE TITLE
Dark Theme Can Be Improved By Changing Color to a Darker One

### ISSUE THREAD

**Issue by seaque** [Lemmings19/fallout-1-walkthrough#1]
The background in dark theme is just gray. Instead of that it could be changed to something like rgb(24, 24, 24), #181818.

**Comment by Lemmings19** [comment]
How's this? They both have a slight yellow/green tint to them, keeping in theme with the game.

![image](https://user-images.githubusercontent.com/3407841/93009523-2e7a6100-f537-11ea-8cff-6e534975bc4d.png)

**Comment by Lemmings19** [comment]
How's this? They both have a slight green/yellow tint to them, keeping in theme with the game.

#2f2d25

![image](https://user-images.githubusercontent.com/3407841/93009550-75685680-f537-11ea-9709-757f48d8c997.png)

**Comment by Lemmings19** [comment]
I've gone ahead and update the dark theme color for both Fallout 1 and 2 guides to `#1e201c`.
